### ISSUE TITLE
demo不能形成倒影？

### ISSUE THREAD

**Issue by Destiny01** [liberty2015/3DViewPagerGallery#1]
![qq 20161021112134](https://cloud.githubusercontent.com/assets/11342391/19585636/b3c19586-9780-11e6-980f-25f940f8b9c7.png)

**Comment by liberty2015** [comment]
这里估计是因为图片过大导致解码的时候出现内存溢出了，需要压缩图片，具体的方法可以看看http://chjmars.iteye.com/blog/1157137
